const DEFAULT_PRODUCTS=[['1 potong ayam original',8000],['1 ayam spicy tanpa nasi',11000],['1 ayam spicy pakai nasi',13000],['1 ayam geprek tanpa nasi',11000],['1 ayam geprek pakai nasi',13000],['1 jamur crispy',5000],['1 tusuk bakso',1000],['1 sambal geprek saja',3000],['1 nasi saja',3000],['1 cup usus ayam',5000],['1 hati rampela',5000]];
const PRODUCTS_KEY='owner_dashboard_products_v2',REPORTS_KEY='owner_dashboard_reports_v2',PROFILE_KEY='owner_dashboard_profile_v2';
const $=id=>document.getElementById(id),money=v=>'Rp'+Math.round(Number(v)||0).toLocaleString('id-ID');
const today=()=>{const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function getProducts(){const p=read(PRODUCTS_KEY,null);if(Array.isArray(p)&&p.length)return p;write(PRODUCTS_KEY,DEFAULT_PRODUCTS);return [...DEFAULT_PRODUCTS]}
function getReports(){return read(REPORTS_KEY,{})}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderProducts(){const p=getProducts();const count=$('productCount');if(count)count.textContent=`${p.length} produk`;if($('productsList'))$('productsList').innerHTML=p.length?p.map((x,i)=>`<div class="product-item"><div><b>${escapeHtml(x[0])}</b><small>${money(x[1])}</small></div><div class="product-actions"><button data-edit-product="${i}" type="button">Edit</button><button data-delete-product="${i}" type="button">Hapus</button></div></div>`).join(''):'<div class="empty-state">Belum ada produk.</div>';document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(Number(b.dataset.editProduct)));document.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(Number(b.dataset.deleteProduct)));renderHomeProducts()}
function renderHomeProducts(){const el=$('homeProductsList');if(!el)return;const p=getProducts();el.innerHTML=p.length?p.slice(0,6).map(x=>`<div class="product-item home-product"><div><b>${escapeHtml(x[0])}</b><small>${money(x[1])}</small></div><span class="home-arrow">›</span></div>`).join(''):'<div class="empty-state">Belum ada produk.</div>'}
function editProduct(i){const p=getProducts()[i];if(!p)return;const name=prompt('Nama produk:',p[0]);if(name===null)return;const price=prompt('Harga (angka):',p[1]);if(price===null)return;const n=Number(price);if(!name.trim()||!Number.isFinite(n)||n<0)return alert('Nama dan harga harus valid.');const all=getProducts();all[i]=[name.trim(),Math.round(n)];write(PRODUCTS_KEY,all);renderProducts();renderSales();calculate()}
function deleteProduct(i){const all=getProducts();if(!all[i])return;if(!confirm(`Hapus produk "${all[i][0]}"?`))return;all.splice(i,1);write(PRODUCTS_KEY,all);renderProducts();renderSales();calculate()}
function addProduct(){const name=prompt('Nama produk:');if(!name?.trim())return;const price=Number(prompt('Harga (angka):','10000'));if(!Number.isFinite(price)||price<0)return alert('Harga tidak valid.');const all=getProducts();all.push([name.trim(),Math.round(price)]);write(PRODUCTS_KEY,all);renderProducts();renderSales();calculate()}
function renderSales(){const p=getProducts();if(!$('salesList'))return;$('salesList').innerHTML=p.map((x,i)=>`<div class="sale-row"><div><div class="sale-name">${escapeHtml(x[0])}</div><div class="sale-price">${money(x[1])} / pcs</div></div><input class="qty-input" data-index="${i}" type="number" min="0" step="1" value="0" inputmode="numeric" aria-label="Jumlah ${escapeHtml(x[0])}"><div class="row-total" id="rowTotal-${i}">${money(0)}</div></div>`).join('');document.querySelectorAll('.qty-input').forEach(x=>x.addEventListener('input',calculate))}
function addExpenseRow(name='',amount=''){const row=document.createElement('div');row.className='expense-row';row.innerHTML=`<input class="expense-input expense-name" type="text" placeholder="Contoh: bahan / transport" value="${escapeHtml(name)}"><input class="expense-input expense-amount" type="number" min="0" step="100" placeholder="Rp0" value="${amount||''}" inputmode="numeric"><button class="expense-remove" type="button" title="Hapus">×</button>`;row.querySelectorAll('input').forEach(x=>x.addEventListener('input',calculate));row.querySelector('.expense-remove').onclick=()=>{row.remove();if(!document.querySelector('.expense-row'))addExpenseRow();calculate()};$('expenseList').appendChild(row)}
function renderExpenses(expenses=[]){if(!$('expenseList'))return;$('expenseList').innerHTML='';if(!expenses.length)addExpenseRow();else expenses.forEach(x=>addExpenseRow(x.name,x.amount))}
function calculate(){const p=getProducts();let income=0;document.querySelectorAll('.qty-input').forEach((input,i)=>{const total=Math.max(0,Number(input.value)||0)*(p[i]?.[1]||0);income+=total;const t=$(`rowTotal-${i}`);if(t)t.textContent=money(total)});let expenses=0;document.querySelectorAll('.expense-amount').forEach(x=>expenses+=Math.max(0,Number(x.value)||0));const profit=income-expenses;if($('incomeSummary'))$('incomeSummary').textContent=money(income);if($('expenseSummary'))$('expenseSummary').textContent=money(expenses);if($('profitSummary'))$('profitSummary').textContent=money(profit);if($('profitTotal'))$('profitTotal').textContent=money(profit);return{income,expenses,profit}}
function getFormData(){const p=getProducts(),t=calculate();return{date:$('reportDate').value||today(),sales:p.map((x,i)=>({name:x[0],price:x[1],qty:Math.max(0,Number(document.querySelector(`[data-index="${i}"]`)?.value)||0)})),expenses:[...document.querySelectorAll('.expense-row')].map(r=>({name:r.querySelector('.expense-name').value.trim(),amount:Math.max(0,Number(r.querySelector('.expense-amount').value)||0)})).filter(x=>x.name||x.amount),...t,updatedAt:new Date().toISOString()}}
function saveReport(){const d=getFormData(),r=getReports();r[d.date]=d;write(REPORTS_KEY,r);renderHistory();renderTrendChart();alert(`Laporan ${d.date} berhasil disimpan.`)}
function loadForm(report){$('reportDate').value=report.date||today();renderSales();document.querySelectorAll('.qty-input').forEach((x,i)=>x.value=report.sales?.[i]?.qty||0);renderExpenses(report.expenses||[]);calculate()}
function openReport(date){const r=getReports()[date];if(r){loadForm(r);showPage('sales');closeMenu()}}
function renderHistory(){const q=($('historySearch')?.value||'').toLowerCase();const entries=Object.values(getReports()).filter(x=>x.date.includes(q)).sort((a,b)=>b.date.localeCompare(a.date));if(!$('historyList'))return;$('historyList').innerHTML=entries.length?entries.map(r=>`<div class="history-item"><div><div class="history-date">${formatDate(r.date)}</div><div class="sale-price">Pendapatan ${money(r.income)} · Pengeluaran ${money(r.expenses)}</div></div><div class="history-actions"><span class="history-profit">${money(r.profit)}</span><button data-open="${r.date}" type="button">Buka</button><button data-delete="${r.date}" type="button">Hapus</button></div></div>`).join(''):'<div class="history-empty">Belum ada laporan tersimpan.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openReport(b.dataset.open));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteReport(b.dataset.delete))}
function deleteReport(date){const r=getReports();if(!r[date])return;if(!confirm(`Hapus laporan ${date}?`))return;delete r[date];write(REPORTS_KEY,r);renderHistory();renderTrendChart()}
function clearHistory(){if(!Object.keys(getReports()).length)return;if(confirm('Hapus semua riwayat laporan?')){localStorage.removeItem(REPORTS_KEY);renderHistory();renderTrendChart()}}
function resetForm(){$('reportDate').value=today();renderSales();renderExpenses();calculate()}
function formatDate(d){return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${d}T00:00:00`))}
function profile(){return read(PROFILE_KEY,{businessName:'',ownerName:'',businessPhone:'',businessDesc:''})}
function loadProfile(){const p=profile();if($('businessName'))$('businessName').value=p.businessName||'';if($('ownerName'))$('ownerName').value=p.ownerName||'';if($('businessPhone'))$('businessPhone').value=p.businessPhone||'';if($('businessDesc'))$('businessDesc').value=p.businessDesc||'';if($('businessTitle'))$('businessTitle').textContent=p.businessName||'Buku Kas Usaha';if($('businessSubtitle'))$('businessSubtitle').textContent=p.businessDesc||'Catat penjualan, pengeluaran, dan hasil usaha dengan rapi.';if($('topbarBusinessName'))$('topbarBusinessName').textContent=p.businessName||'Owner Dashboard'}
function saveProfile(){const p={businessName:$('businessName').value.trim(),ownerName:$('ownerName').value.trim(),businessPhone:$('businessPhone').value.trim(),businessDesc:$('businessDesc').value.trim()};write(PROFILE_KEY,p);loadProfile();closeMenu();showPage('home');alert('Profil usaha berhasil disimpan.')}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function backup(){download(`owner-dashboard-backup-${today()}.json`,JSON.stringify({version:2,exportedAt:new Date().toISOString(),profile:profile(),products:getProducts(),reports:getReports()},null,2),'application/json');closeMenu()}
function restore(file){const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);if(!d||!Array.isArray(d.products)||!d.reports)return alert('File backup tidak valid.');write(PROFILE_KEY,d.profile||{});write(PRODUCTS_KEY,d.products);write(REPORTS_KEY,d.reports);loadProfile();renderProducts();renderSales();renderHistory();renderExpenses();calculate();renderTrendChart();alert('Backup berhasil dipulihkan.')}catch{alert('Backup tidak dapat dibaca.')}};reader.readAsText(file)}
function exportCSV(){const rows=[['Tanggal','Omzet','Pengeluaran','Keuntungan'],...Object.values(getReports()).sort((a,b)=>a.date.localeCompare(b.date)).map(r=>[r.date,r.income,r.expenses,r.profit])];download(`laporan-usaha-${today()}.csv`,rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv;charset=utf-8');closeMenu()}
function showPage(name){document.querySelectorAll('[data-page-view]').forEach(p=>p.classList.toggle('active',p.dataset.pageView===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='home'){calculate();renderTrendChart();renderHomeProducts()}closeMenu()}
function renderTrendChart(){const el=$('trendChart');if(!el)return;const reports=Object.values(getReports()).filter(r=>r&&r.date).sort((a,b)=>a.date.localeCompare(b.date)).slice(-14);if(!reports.length){el.innerHTML='<div class="chart-empty">Belum ada laporan tersimpan untuk dianalisis.</div>';return}const w=860,h=290,pad={l:46,r:18,t:20,b:42};const innerW=w-pad.l-pad.r,innerH=h-pad.t-pad.b;const max=Math.max(1,...reports.flatMap(r=>[Number(r.income)||0,Number(r.profit)||0]));const min=Math.min(0,...reports.map(r=>Number(r.profit)||0));const range=Math.max(1,max-min);const x=i=>pad.l+(reports.length===1?innerW/2:i*innerW/(reports.length-1));const y=v=>pad.t+(max-v)*innerH/range;const fmt=d=>new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short'}).format(new Date(`${d}T00:00:00`));const points=(key)=>reports.map((r,i)=>`${x(i).toFixed(1)},${y(Number(r[key])||0).toFixed(1)}`).join(' ');const grid=[0,.25,.5,.75,1].map(t=>{const v=max-range*t;return `<line x1="${pad.l}" y1="${y(v)}" x2="${w-pad.r}" y2="${y(v)}" class="chart-grid"/><text x="${pad.l-9}" y="${y(v)+4}" text-anchor="end" class="chart-axis">${money(v)}</text>`}).join('');const labels=reports.map((r,i)=>{if(reports.length>7&&i%2!==0)return '';return `<text x="${x(i)}" y="${h-12}" text-anchor="middle" class="chart-label">${fmt(r.date)}</text>`}).join('');const dots=(key,cls)=>reports.map((r,i)=>`<circle cx="${x(i)}" cy="${y(Number(r[key])||0)}" r="4" class="${cls}"/>`).join('');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Grafik omzet dan keuntungan harian"><g>${grid}</g><polyline points="${points('income')}" class="chart-line chart-income"/><polyline points="${points('profit')}" class="chart-line chart-profit"/>${dots('income','chart-dot chart-income-dot')}${dots('profit','chart-dot chart-profit-dot')}<g>${labels}</g></svg><div class="chart-last"><span>Terakhir: <b>${formatDate(reports[reports.length-1].date)}</b></span><span>Omzet <b>${money(reports[reports.length-1].income)}</b></span><span>Profit <b>${money(reports[reports.length-1].profit)}</b></span></div>`}
function closeMenu(){const menu=$('sideMenu'),toggle=$('menuToggle');if(!menu||!toggle)return;menu.classList.remove('open');menu.setAttribute('aria-hidden','true');toggle.setAttribute('aria-expanded','false')}
function toggleMenu(){const menu=$('sideMenu'),toggle=$('menuToggle');if(!menu||!toggle)return;const open=!menu.classList.contains('open');menu.classList.toggle('open',open);menu.setAttribute('aria-hidden',String(!open));toggle.setAttribute('aria-expanded',String(open))}
function bindMenu(){const toggle=$('menuToggle'),close=$('menuClose');if(toggle)toggle.addEventListener('click',e=>{e.stopPropagation();toggleMenu()});if(close)close.addEventListener('click',e=>{e.stopPropagation();closeMenu()});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelector('[data-menu-action="backup"]')?.addEventListener('click',backup);document.querySelector('[data-menu-action="export"]')?.addEventListener('click',exportCSV);document.addEventListener('click',e=>{const menu=$('sideMenu');if(menu?.classList.contains('open')&&!menu.contains(e.target)&&!toggle?.contains(e.target))closeMenu()})}
$('reportDate').value=today();loadProfile();renderProducts();renderSales();renderExpenses();renderHistory();calculate();renderTrendChart();
$('addProduct').onclick=addProduct;$('addExpense').onclick=()=>addExpenseRow();$('saveReport').onclick=saveReport;$('clearForm').onclick=resetForm;$('clearHistory').onclick=clearHistory;$('saveSettings').onclick=saveProfile;$('exportHistory').onclick=exportCSV;$('restoreBackup').onclick=()=>$('backupFile').click();$('backupSettings').onclick=backup;$('backupFile').onchange=e=>e.target.files[0]&&restore(e.target.files[0]);$('historySearch').oninput=renderHistory;bindMenu();$('reportDate').onchange=()=>{const r=getReports()[$('reportDate').value];if(r)loadForm(r)};
