(function(){
  const money=v=>'Rp'+Math.round(Number(v)||0).toLocaleString('id-ID');
  const getTotals=()=>Object.values(getReports()).reduce((t,r)=>({income:t.income+(Number(r.income)||0),expenses:t.expenses+(Number(r.expenses)||0),profit:t.profit+(Number(r.profit)||0)}),{income:0,expenses:0,profit:0});
  window.renderHomeTotals=function(){const t=getTotals();const income=document.getElementById('incomeSummary'),expenses=document.getElementById('expenseSummary'),profit=document.getElementById('profitSummary');if(income)income.textContent=money(t.income);if(expenses)expenses.textContent=money(t.expenses);if(profit)profit.textContent=money(t.profit)};
  const originalSave=window.saveReport;if(typeof originalSave==='function'){const saveButton=document.getElementById('saveReport');if(saveButton)saveButton.onclick=function(){originalSave();renderHomeTotals()}}
  const originalClear=window.clearHistory;if(typeof originalClear==='function'){const clearButton=document.getElementById('clearHistory');if(clearButton)clearButton.onclick=function(){originalClear();renderHomeTotals()}}
  const originalDelete=window.deleteReport;if(typeof originalDelete==='function'){window.deleteReport=function(date){originalDelete(date);renderHomeTotals()};if(typeof window.renderHistory==='function')window.renderHistory()}
  document.querySelectorAll('[data-page="home"]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(renderHomeTotals,0)));renderHomeTotals();
  document.addEventListener('click',e=>{const item=e.target.closest('.home-product');if(!item)return;e.preventDefault();if(typeof window.showPage==='function')window.showPage('products')});

  const style=document.createElement('style');style.textContent=`
    .chart-y-axis-left,.chart-y-axis-right{width:84px!important}.chart-y-axis-left span{right:8px!important}.chart-y-axis-right span{left:8px!important;right:auto!important}.chart-stage{overflow:hidden!important}.chart-stage svg{overflow:hidden!important}.chart-candles{clip-path:inset(0 0 0 0)}.chart-candle-body{shape-rendering:geometricPrecision}.chart-label{paint-order:stroke;stroke:rgba(7,20,38,.8);stroke-width:3px}
    .home-product{cursor:pointer;user-select:none;-webkit-tap-highlight-color:transparent;transition:transform .18s ease,background .18s ease}.home-product:active{transform:scale(.985)}.home-product .home-arrow{transition:transform .18s ease}.home-product:hover .home-arrow{transform:translateX(4px)}
    #opsRoot .ops-card,#opsRoot .ops-stat,#opsRoot .ops-row,#opsRoot .ops-empty{background:linear-gradient(145deg,rgba(15,35,59,.86),rgba(5,18,33,.92));border-color:rgba(88,166,255,.16);box-shadow:0 10px 28px rgba(0,0,0,.14)}
    #opsRoot .ops-form input,#opsRoot .ops-form select,#opsRoot .ops-recipe-row input,#opsRoot .ops-recipe-row select{appearance:none;-webkit-appearance:none;color:#eaf4ff;background:linear-gradient(180deg,#0b2139,#071426);border:1px solid rgba(88,166,255,.24);box-shadow:inset 0 1px 0 rgba(255,255,255,.035),0 4px 16px rgba(0,0,0,.12);color-scheme:dark}
    #opsRoot .ops-form select,#opsRoot .ops-recipe-row select{background-image:linear-gradient(45deg,transparent 50%,#83bfff 50%),linear-gradient(135deg,#83bfff 50%,transparent 50%),linear-gradient(180deg,#0b2139,#071426);background-position:calc(100% - 16px) 50%,calc(100% - 11px) 50%,0 0;background-size:5px 5px,5px 5px,100% 100%;background-repeat:no-repeat;padding-right:34px}
    #opsRoot .ops-form option,#opsRoot .ops-recipe-row option{background:#071426;color:#eaf4ff}#opsRoot .ops-form input:focus,#opsRoot .ops-form select:focus,#opsRoot .ops-recipe-row input:focus,#opsRoot .ops-recipe-row select:focus{border-color:rgba(88,166,255,.7);box-shadow:0 0 0 3px rgba(88,166,255,.1)}
    #opsRoot .ops-btn{background:linear-gradient(135deg,#2c8cff,#1768cf);color:#fff;border:1px solid rgba(137,196,255,.24);box-shadow:0 8px 18px rgba(20,105,210,.18)}#opsRoot .ops-btn.secondary{background:rgba(9,30,51,.82);color:#dbeeff;border-color:rgba(88,166,255,.2);box-shadow:none}#opsRoot .ops-btn.danger{background:rgba(105,25,38,.72);border-color:rgba(255,105,125,.18)}#opsRoot .ops-tabs{scrollbar-width:none}#opsRoot .ops-tabs::-webkit-scrollbar{display:none}
    .side-menu .menu-logout{margin-top:auto!important;position:relative!important;bottom:auto!important;flex:0 0 auto!important;order:9999!important;background:linear-gradient(180deg,rgba(10,25,43,.98),rgba(5,15,28,.99))!important;border-top:1px solid rgba(139,177,214,.16)!important}

    /* Account avatar: the old square is replaced by a real profile button. */
    #accountCenterNative{position:relative;margin-left:auto;z-index:1200}
    #accountButtonNative{width:54px!important;height:54px!important;padding:0!important;border-radius:50%!important;border:1px solid rgba(111,181,255,.38)!important;background:linear-gradient(145deg,#12345a,#071426)!important;box-shadow:0 8px 24px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.08)!important;overflow:hidden!important;display:grid!important;place-items:center!important;cursor:pointer!important;-webkit-tap-highlight-color:transparent!important}
    #accountButtonNative .profile-avatar-img,#accountButtonNative .profile-avatar-initial{width:100%;height:100%;display:grid;place-items:center}
    #accountButtonNative .profile-avatar-img{object-fit:cover}
    #accountButtonNative .profile-avatar-initial{font-size:19px;font-weight:800;color:#dff1ff;background:radial-gradient(circle at 35% 25%,#4ba7ff,#1160bd 65%,#08264a)}
    .account-panel-native{width:min(320px,calc(100vw - 28px))!important;padding:14px!important;border-radius:20px!important;background:linear-gradient(155deg,rgba(12,31,53,.98),rgba(4,15,28,.99))!important;border:1px solid rgba(106,178,255,.22)!important;box-shadow:0 20px 60px rgba(0,0,0,.42)!important;backdrop-filter:blur(18px)!important}
    .account-head-native{display:flex!important;align-items:center!important;gap:12px!important;padding:4px 4px 12px!important}
    #accountAvatarNative{width:46px!important;height:46px!important;flex:0 0 46px!important;border-radius:50%!important;overflow:hidden!important;display:grid!important;place-items:center!important;background:#0c2c4e!important;border:1px solid rgba(111,181,255,.3)!important}
    #accountAvatarNative img{width:100%;height:100%;object-fit:cover}.account-head-native b{display:block}.account-head-native small{display:block;margin-top:3px;opacity:.7}
    .account-panel-native>button{width:100%!important;text-align:left!important;padding:13px 12px!important;border:0!important;border-radius:12px!important;background:transparent!important;color:#eaf4ff!important;font:inherit!important;cursor:pointer!important}
    .account-panel-native>button:hover,.account-panel-native>button:active{background:rgba(79,157,235,.12)!important}

    /* Shop profile editor. */
    .profile-editor-card{display:grid;grid-template-columns:auto 1fr;gap:16px;align-items:center;padding:16px;margin:0 0 20px;border:1px solid rgba(88,166,255,.17);border-radius:18px;background:linear-gradient(145deg,rgba(15,35,59,.72),rgba(5,18,33,.8))}
    .profile-photo-wrap{position:relative;width:82px;height:82px}.profile-photo-preview{width:82px;height:82px;border-radius:50%;overflow:hidden;display:grid;place-items:center;background:radial-gradient(circle at 35% 25%,#4ba7ff,#1160bd 65%,#08264a);border:2px solid rgba(120,194,255,.35);box-shadow:0 8px 24px rgba(0,0,0,.25);font-size:28px;font-weight:800;color:#e8f5ff}.profile-photo-preview img{width:100%;height:100%;object-fit:cover}.profile-photo-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.profile-photo-actions label,.profile-photo-actions button{font:inherit;font-size:12px;font-weight:700;padding:8px 10px;border-radius:10px;border:1px solid rgba(88,166,255,.24);background:rgba(10,31,52,.8);color:#dff0ff;cursor:pointer}.profile-photo-actions input{display:none}.profile-editor-copy b{display:block;font-size:16px}.profile-editor-copy p{margin:5px 0 0;color:#8ea5bd;font-size:13px;line-height:1.45}
    @media(max-width:560px){.profile-editor-card{grid-template-columns:1fr}.profile-photo-wrap{width:100%;height:auto;display:flex;align-items:center;gap:12px}.profile-photo-preview{width:72px;height:72px;flex:0 0 72px}.profile-photo-actions{margin-top:0}.account-panel-native{right:0!important;left:auto!important}}
  `;document.head.appendChild(style);

  /* Profile/photo system: stays local to the device, matching the current app architecture. */
  const PROFILE_KEY='owner_dashboard_profile_v2';
  const readProfile=()=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')||{}}catch{return{}}};
  const writeProfile=p=>localStorage.setItem(PROFILE_KEY,JSON.stringify(p));
  const initials=name=>(String(name||'Owner').trim().split(/\\s+/).map(x=>x[0]).join('').slice(0,2)||'O').toUpperCase();
  let pendingPhoto=null;
  function avatarMarkup(p,large=false){return p.photo?`<img class="${large?'profile-photo-image':'profile-avatar-img'}" src="${p.photo}" alt="Foto profil">`:`<span class="${large?'profile-photo-initial':'profile-avatar-initial'}">${initials(p.ownerName||p.businessName||'Owner')}</span>`}
  function renderAccountProfile(){const p=readProfile(),btn=document.getElementById('accountButtonNative'),av=document.getElementById('accountAvatarNative');if(btn)btn.innerHTML=avatarMarkup(p);if(av)av.innerHTML=avatarMarkup(p);const n=document.getElementById('accountNameNative'),r=document.getElementById('accountRoleNative');if(n)n.textContent=p.ownerName||'Owner';if(r)r.textContent='Owner';}
  function injectProfileEditor(){const card=document.querySelector('.settings-card');if(!card||document.getElementById('profileEditorCard'))return;const head=card.querySelector('.section-head');const el=document.createElement('div');el.id='profileEditorCard';el.className='profile-editor-card';el.innerHTML=`<div class="profile-photo-wrap"><div id="profilePhotoPreview" class="profile-photo-preview"></div><div class="profile-photo-actions"><label>📷 Ganti foto<input id="profilePhotoInput" type="file" accept="image/*"></label><button id="removeProfilePhoto" type="button">Hapus</button></div></div><div class="profile-editor-copy"><b>Profil toko & pemilik</b><p>Pasang foto profil toko, lalu atur nama usaha dan identitasnya di bawah. Foto disimpan di perangkat ini.</p></div>`;head?.insertAdjacentElement('afterend',el);renderProfileEditor();
    const input=document.getElementById('profilePhotoInput');input?.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>8*1024*1024){alert('Foto maksimal 8 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=512,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);pendingPhoto=c.toDataURL('image/webp',.82);renderProfileEditor()};img.src=reader.result};reader.readAsDataURL(file)});
    document.getElementById('removeProfilePhoto')?.addEventListener('click',()=>{pendingPhoto='';const p=readProfile();p.photo='';writeProfile(p);renderAccountProfile();renderProfileEditor()});
    document.getElementById('saveSettings')?.addEventListener('click',()=>{const p=readProfile();if(pendingPhoto!==null){p.photo=pendingPhoto;writeProfile(p);pendingPhoto=null}setTimeout(()=>{renderAccountProfile();renderProfileEditor()},0)});
  }
  function renderProfileEditor(){const box=document.getElementById('profilePhotoPreview');if(!box)return;const p=readProfile();if(pendingPhoto!==null){box.innerHTML=pendingPhoto?`<img src="${pendingPhoto}" alt="Preview foto profil">`:`<span class="profile-photo-initial">${initials(p.ownerName||p.businessName||'Owner')}</span>`}else box.innerHTML=avatarMarkup(p,true);}
  function enhanceProfilePage(){const h=document.querySelector('.page-settings .page-heading h1');const p=document.querySelector('.page-settings .page-heading p');if(h)h.textContent='Edit Profil Toko';if(p)p.textContent='Ganti nama toko, foto profil, identitas pemilik, dan informasi usaha.';injectProfileEditor();renderAccountProfile()}
  document.addEventListener('DOMContentLoaded',()=>{enhanceProfilePage();setTimeout(enhanceProfilePage,80);setTimeout(enhanceProfilePage,300)});

  if(!window.__pieceStockLoaded){window.__pieceStockLoaded=true;const p=document.createElement('script');p.src='piece-stock.js?v=20260926a';p.defer=true;document.body.appendChild(p)}
})();
