(function(){
  const money=v=>'Rp'+Math.round(Number(v)||0).toLocaleString('id-ID');
  const getTotals=()=>Object.values(getReports()).reduce((t,r)=>({income:t.income+(Number(r.income)||0),expenses:t.expenses+(Number(r.expenses)||0),profit:t.profit+(Number(r.profit)||0)}),{income:0,expenses:0,profit:0});
  window.renderHomeTotals=function(){const t=getTotals();const income=document.getElementById('incomeSummary'),expenses=document.getElementById('expenseSummary'),profit=document.getElementById('profitSummary');if(income)income.textContent=money(t.income);if(expenses)expenses.textContent=money(t.expenses);if(profit)profit.textContent=money(t.profit)};
  const originalSave=window.saveReport;if(typeof originalSave==='function'){const saveButton=document.getElementById('saveReport');if(saveButton)saveButton.onclick=function(){originalSave();renderHomeTotals()}}
  const originalClear=window.clearHistory;if(typeof originalClear==='function'){const clearButton=document.getElementById('clearHistory');if(clearButton)clearButton.onclick=function(){originalClear();renderHomeTotals()}}
  const originalDelete=window.deleteReport;if(typeof originalDelete==='function'){window.deleteReport=function(date){originalDelete(date);renderHomeTotals()};if(typeof window.renderHistory==='function')window.renderHistory()}
  document.querySelectorAll('[data-page="home"]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(renderHomeTotals,0)));renderHomeTotals();
  document.addEventListener('click',e=>{const item=e.target.closest('.home-product');if(!item)return;e.preventDefault();if(typeof window.showPage==='function')window.showPage('products')});
  const style=document.createElement('style');style.textContent=`
    .chart-y-axis-left,.chart-y-axis-right{width:84px!important}.chart-y-axis-left span{right:8px!important}.chart-y-axis-right span{left:8px!important;right:auto!important}.chart-stage{overflow:hidden!important}.chart-stage svg{overflow:hidden!important}.chart-candles{clip-path:inset(0 0 0 0)}.chart-candle-body{shape-rendering:geometricPrecision}.chart-label{paint-order:stroke;stroke:rgba(7,20,38,.8);stroke-width:3px}
    .home-product{cursor:pointer;user-select:none;-webkit-tap-highlight-color:transparent;transition:transform .18s ease,background .18s ease}.home-product:active{transform:scale(.985)}.home-product .home-arrow{transition:transform .18s ease}.home-product:hover .home-arrow{transform:translateX(4px)}
    #opsRoot .ops-card,#opsRoot .ops-stat,#opsRoot .ops-row,#opsRoot .ops-empty{background:linear-gradient(145deg,rgba(15,35,59,.86),rgba(5,18,33,.92));border-color:rgba(88,166,255,.16);box-shadow:0 10px 28px rgba(0,0,0,.14)}
    #opsRoot .ops-form input,#opsRoot .ops-form select,#opsRoot .ops-recipe-row input,#opsRoot .ops-recipe-row select{appearance:none;-webkit-appearance:none;color:#eaf4ff;background:linear-gradient(180deg,#0b2139,#071426);border:1px solid rgba(88,166,255,.24);box-shadow:inset 0 1px 0 rgba(255,255,255,.035),0 4px 16px rgba(0,0,0,.12);color-scheme:dark}
    #opsRoot .ops-form select,#opsRoot .ops-recipe-row select{background-image:linear-gradient(45deg,transparent 50%,#83bfff 50%),linear-gradient(135deg,#83bfff 50%,transparent 50%),linear-gradient(180deg,#0b2139,#071426);background-position:calc(100% - 16px) 50%,calc(100% - 11px) 50%,0 0;background-size:5px 5px,5px 5px,100% 100%;background-repeat:no-repeat;padding-right:34px}
    #opsRoot .ops-form option,#opsRoot .ops-recipe-row option{background:#071426;color:#eaf4ff}#opsRoot .ops-form input:focus,#opsRoot .ops-form select:focus,#opsRoot .ops-recipe-row input:focus,#opsRoot .ops-recipe-row select:focus{border-color:rgba(88,166,255,.7);box-shadow:0 0 0 3px rgba(88,166,255,.1)}
    #opsRoot .ops-btn{background:linear-gradient(135deg,#2c8cff,#1768cf);color:#fff;border:1px solid rgba(137,196,255,.24);box-shadow:0 8px 18px rgba(20,105,210,.18)}#opsRoot .ops-btn.secondary{background:rgba(9,30,51,.82);color:#dbeeff;border-color:rgba(88,166,255,.2);box-shadow:none}#opsRoot .ops-btn.danger{background:rgba(105,25,38,.72);border-color:rgba(255,105,125,.18)}#opsRoot .ops-tabs{scrollbar-width:none}#opsRoot .ops-tabs::-webkit-scrollbar{display:none}
    .side-menu .menu-logout{margin-top:auto!important;position:relative!important;bottom:auto!important;flex:0 0 auto!important;order:9999!important;background:linear-gradient(180deg,rgba(10,25,43,.98),rgba(5,15,28,.99))!important;border-top:1px solid rgba(139,177,214,.16)!important}
    /* PROFILE BUTTON: left side, directly beside the store name. Hamburger stays on the right. */
    .topbar-inner{position:relative!important;display:flex!important;align-items:center!important}
    #accountCenterNative{order:-2!important;position:relative!important;left:auto!important;right:auto!important;top:auto!important;bottom:auto!important;margin:0 12px 0 0!important;flex:0 0 auto!important;z-index:80!important}
    #accountButtonNative{width:46px!important;height:46px!important;border-radius:14px!important;display:grid!important;place-items:center!important;padding:0!important;overflow:hidden!important;background:linear-gradient(145deg,#0877e8,#1557c5)!important;border:1px solid rgba(132,197,255,.28)!important;color:#fff!important;font-size:20px!important;box-shadow:0 8px 22px rgba(0,72,170,.22)!important;cursor:pointer!important}
    #accountButtonNative.has-avatar{font-size:0!important;background-position:center!important;background-size:cover!important;background-repeat:no-repeat!important}
    .account-panel-native{position:absolute!important;left:0!important;right:auto!important;top:56px!important;width:min(290px,calc(100vw - 32px))!important;border-radius:18px!important;padding:10px!important;background:linear-gradient(145deg,rgba(10,29,49,.98),rgba(4,14,26,.99))!important;border:1px solid rgba(100,170,235,.2)!important;box-shadow:0 20px 55px rgba(0,0,0,.45)!important;backdrop-filter:blur(18px)!important;-webkit-backdrop-filter:blur(18px)!important}
    .account-panel-native[hidden]{display:none!important}.account-head-native{display:flex!important;align-items:center!important;gap:12px!important;padding:8px!important}.account-head-native>div:first-child{width:44px!important;height:44px!important;border-radius:13px!important;display:grid!important;place-items:center!important;overflow:hidden!important;background:linear-gradient(145deg,#0d78eb,#1760c7)!important;color:#fff!important}.account-head-native>div:first-child.has-avatar{font-size:0!important;background-size:cover!important;background-position:center!important}.account-panel-native hr{border:0!important;border-top:1px solid rgba(140,180,220,.12)!important;margin:6px 0!important}.account-panel-native>button{width:100%!important;text-align:left!important;border:0!important;border-radius:12px!important;background:transparent!important;color:#e6f2ff!important;padding:12px!important;font:inherit!important;cursor:pointer!important}.account-panel-native>button:hover,.account-panel-native>button:active{background:rgba(75,145,220,.12)!important}.account-panel-native small{display:block!important;color:#88a6c5!important;margin-top:2px!important}
    #profileUploadField{display:flex;align-items:center;gap:14px;margin:0 0 18px;padding:14px;border:1px solid rgba(88,166,255,.16);border-radius:16px;background:rgba(8,27,47,.6)}#profilePreview{width:64px;height:64px;border-radius:18px;object-fit:cover;display:block;background:linear-gradient(145deg,#0877e8,#1557c5);border:1px solid rgba(132,197,255,.24)}#profileUploadField label{display:block;color:#b8cce0;font-size:13px;line-height:1.45}#profileUploadInput{display:block;margin-top:7px;width:100%;color:#dcecff}
    @media(max-width:520px){#accountCenterNative{margin-right:9px!important}.account-panel-native{top:54px!important}.brand{min-width:0!important}.brand>span:last-child{min-width:0!important}}
  `;document.head.appendChild(style);

  /* Move the profile control to the left, beside the business name. */
  const topbar=document.querySelector('.topbar-inner');
  const account=document.getElementById('accountCenterNative');
  const brand=document.querySelector('.brand');
  if(topbar&&account&&brand){topbar.insertBefore(account,brand);}

  const PROFILE_KEY='owner_dashboard_profile_v1';
  const readProfile=()=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}};
  const applyProfile=()=>{const p=readProfile();const avatar=document.getElementById('accountButtonNative');const head=document.getElementById('accountAvatarNative');if(p.photo){if(avatar){avatar.classList.add('has-avatar');avatar.style.backgroundImage=`url("${p.photo}")`;avatar.textContent=''}if(head){head.classList.add('has-avatar');head.style.backgroundImage=`url("${p.photo}")`;head.textContent=''}}else{if(avatar){avatar.classList.remove('has-avatar');avatar.style.backgroundImage='';avatar.textContent='▣'}if(head){head.classList.remove('has-avatar');head.style.backgroundImage='';head.textContent='▣'}}if(p.name){const title=document.getElementById('businessTitle');const topName=document.getElementById('topbarBusinessName');if(title)title.textContent=p.name;if(topName)topName.textContent=p.name;const input=document.getElementById('businessName');if(input&&!input.value)input.value=p.name}if(p.owner){const input=document.getElementById('ownerName');if(input&&!input.value)input.value=p.owner}if(p.phone){const input=document.getElementById('businessPhone');if(input&&!input.value)input.value=p.phone}if(p.desc){const input=document.getElementById('businessDesc');if(input&&!input.value)input.value=p.desc}if(p.owner){const n=document.getElementById('accountNameNative');if(n)n.textContent=p.owner}};
  const injectProfileUpload=()=>{const card=document.querySelector('.settings-card');const grid=document.querySelector('.settings-grid');if(!card||!grid||document.getElementById('profileUploadField'))return;const field=document.createElement('div');field.id='profileUploadField';field.innerHTML='<img id="profilePreview" alt="Foto profil toko"><label>Foto profil toko<input id="profileUploadInput" type="file" accept="image/*"><small>Pilih foto/logo toko. Gambar akan disimpan di perangkat ini.</small></label>';grid.parentNode.insertBefore(field,grid);const input=document.getElementById('profileUploadInput');const preview=document.getElementById('profilePreview');const p=readProfile();preview.src=p.photo||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2264%22 height=%2264%22 viewBox=%220 0 64 64%22%3E%3Crect width=%2264%22 height=%2264%22 rx=%2218%22 fill=%22%23155fbd%22/%3E%3Ctext x=%2232%22 y=%2240%22 text-anchor=%22middle%22 font-size=%2226%22 fill=%22white%22%3E%F0%9F%91%A4%3C/text%3E%3C/svg%3E';input.addEventListener('change',()=>{const file=input.files&&input.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=256,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.78);localStorage.setItem(PROFILE_KEY,JSON.stringify({...readProfile(),photo:data}));preview.src=data;applyProfile()};img.src=reader.result};reader.readAsDataURL(file)});};
  const openProfile=()=>{if(typeof window.showPage==='function')window.showPage('settings');else document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.classList.contains('page-settings')));setTimeout(()=>{injectProfileUpload();applyProfile();document.getElementById('businessName')?.focus()},50)};
  document.addEventListener('click',e=>{const b=e.target.closest('[data-account-native="profile"]');if(b){e.preventDefault();e.stopPropagation();openProfile()}});
  const save=document.getElementById('saveSettings');if(save)save.addEventListener('click',()=>{const p=readProfile();localStorage.setItem(PROFILE_KEY,JSON.stringify({...p,name:document.getElementById('businessName')?.value.trim()||'',owner:document.getElementById('ownerName')?.value.trim()||'',phone:document.getElementById('businessPhone')?.value.trim()||'',desc:document.getElementById('businessDesc')?.value.trim()||''}));applyProfile();});
  applyProfile();
  if(!window.__pieceStockLoaded){window.__pieceStockLoaded=true;const p=document.createElement('script');p.src='piece-stock.js?v=20260926a';p.defer=true;document.body.appendChild(p)}
})();
