/* Team + Inventory layer for Owner Dashboard V2. Auth is handled by auth.js. */
(() => {
  const K={users:'owner_dashboard_users_v1',session:'owner_dashboard_session_v1',stock:'owner_dashboard_stock_v1',queue:'owner_dashboard_staff_queue_v1'};
  const $=id=>document.getElementById(id);
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const money=v=>'Rp'+Math.round(Number(v)||0).toLocaleString('id-ID');
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const roles={owner:'Owner',manager:'Manager',kitchen:'Kitchen',waiter:'Waiter'};
  function users(){return read(K.users,[])}
  function session(){return read(K.session,null)}
  function addQueue(type,payload){const q=read(K.queue,[]);q.unshift({id:uid(),type,payload,by:session()?.name||'Staff',role:session()?.role||'',createdAt:new Date().toISOString(),status:'pending'});write(K.queue,q)}
  function stock(){return read(K.stock,[])}
  function injectStyles(){if($('teamStyles'))return;const s=document.createElement('style');s.id='teamStyles';s.textContent=`#teamLogin{display:none}.team-badge{display:none!important}.team-panel{margin:0 0 18px}.team-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}.team-box{padding:14px;border-radius:16px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08)}.team-box b{display:block;margin-bottom:4px}.team-box small{opacity:.65}.team-form{display:grid;gap:9px}.team-form input,.team-form select{padding:11px;border-radius:10px;border:1px solid rgba(255,255,255,.12);background:#071426;color:#fff}.team-btn{padding:10px 13px;border:0;border-radius:10px;background:#fff;color:#071426;font-weight:700}.team-btn.danger{background:#5b1720;color:#fff}.team-list{display:grid;gap:8px;margin-top:10px}.team-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px;border-radius:12px;background:rgba(255,255,255,.035)}.team-row span{opacity:.7;font-size:12px}.team-actions{display:flex;gap:6px;flex-wrap:wrap}.team-actions button{padding:7px 9px;border-radius:9px;border:1px solid rgba(255,255,255,.12);background:transparent;color:inherit}.queue-item{padding:12px;border-radius:12px;background:rgba(255,255,255,.035);margin-top:8px}.queue-item small{opacity:.65}.team-locked{opacity:.5;pointer-events:none}@media(max-width:600px){.team-grid{grid-template-columns:1fr}.team-row{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(s)}
  function moveLogoutToBottom(){const menu=document.getElementById('sideMenu');const logout=menu?.querySelector('[data-menu-action="logout"]');if(menu&&logout)menu.appendChild(logout)}
  function addPages(){if(document.querySelector('[data-page-view="team"]')){moveLogoutToBottom();return}const main=document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.className='page page-team';sec.dataset.pageView='team';sec.innerHTML=`<div class="page-heading"><span class="eyebrow">TEAM OPS</span><h1>Operasional</h1><p>Stok, HPP, dan laporan dari Kitchen & Waiter.</p></div><section class="card team-panel"><div class="section-head"><div><span class="eyebrow">STOK</span><h2>Persediaan</h2></div><button id="addStock" class="team-btn">+ Stok</button></div><div id="stockList" class="team-list"></div></section><section class="card team-panel"><div class="section-head"><div><span class="eyebrow">AKTIVITAS</span><h2>Masuk ke Owner</h2></div></div><div id="queueList" class="team-list"></div></section><section id="staffTools" class="card team-panel"><div class="section-head"><div><span class="eyebrow">AKUN</span><h2>Team Access</h2></div><button id="addStaff" class="team-btn">+ Akun</button></div><div id="staffList" class="team-list"></div></section>`;const footer=main.querySelector('footer');main.insertBefore(sec,footer);document.querySelector('.topbar .menu-wrap .side-menu')?.insertAdjacentHTML('beforeend','<button class="menu-item" data-page="team" type="button"><span>🧑‍🍳</span><div><b>Operasional</b><small>Stok, HPP & aktivitas team</small></div></button>');moveLogoutToBottom()}
  function renderStock(){const el=$('stockList');if(!el)return;const s=stock();el.innerHTML=s.length?s.map((x,i)=>`<div class="team-row"><div><b>${esc(x.name)}</b><span>${Number(x.qty)||0} ${esc(x.unit)} · ${money(x.cost||0)}/unit</span></div><div class="team-actions"><button data-stock-minus="${i}">−</button><button data-stock-plus="${i}">+</button><button data-stock-del="${i}">Hapus</button></div></div>`).join(''):'<div class="history-empty">Belum ada stok.</div>';el.querySelectorAll('[data-stock-plus]').forEach(b=>b.onclick=()=>changeStock(+b.dataset.stockPlus,1));el.querySelectorAll('[data-stock-minus]').forEach(b=>b.onclick=()=>changeStock(+b.dataset.stockMinus,-1));el.querySelectorAll('[data-stock-del]').forEach(b=>b.onclick=()=>deleteStock(+b.dataset.stockDel))}
  function changeStock(i,delta){const s=stock();if(!s[i])return;const amount=Math.abs(Number(prompt(`Jumlah ${delta>0?'masuk':'keluar'} (${s[i].unit}):`,'1'))||0);if(!amount)return;s[i].qty=Math.max(0,(Number(s[i].qty)||0)+delta*amount);write(K.stock,s);addQueue(delta>0?'stock_in':'stock_out',{name:s[i].name,qty:amount,unit:s[i].unit});renderStock();renderQueue()}
  function deleteStock(i){const s=stock();if(!s[i])return;if(confirm(`Hapus ${s[i].name}?`)){s.splice(i,1);write(K.stock,s);renderStock()}}
  function addStock(){const name=prompt('Nama bahan:','Ayam');if(!name?.trim())return;const qty=Number(prompt('Stok awal:','1'));const unit=prompt('Satuan (kg/L/pcs):','kg');const cost=Number(prompt(`Harga per ${unit}:`,'0'));if(!Number.isFinite(qty)||!Number.isFinite(cost))return;const s=stock();s.push({id:uid(),name:name.trim(),qty:Math.max(0,qty),unit:unit||'unit',cost:Math.max(0,cost)});write(K.stock,s);addQueue('stock_created',{name:name.trim(),qty,unit,cost});renderStock();renderQueue()}
  function renderQueue(){const el=$('queueList');if(!el)return;const q=read(K.queue,[]);el.innerHTML=q.length?q.slice(0,30).map(x=>`<div class="queue-item"><b>${esc(x.type.replaceAll('_',' '))}</b> · ${esc(x.by)}<br><small>${esc(JSON.stringify(x.payload))} · ${new Date(x.createdAt).toLocaleString('id-ID')}</small>${session()?.role==='owner'&&x.status==='pending'?`<div class="team-actions"><button data-q-ok="${x.id}">Terima</button><button data-q-del="${x.id}">Hapus</button></div>`:''}</div>`).join(''):'<div class="history-empty">Belum ada aktivitas masuk.</div>';el.querySelectorAll('[data-q-ok]').forEach(b=>b.onclick=()=>queueStatus(b.dataset.qOk,'approved'));el.querySelectorAll('[data-q-del]').forEach(b=>b.onclick=()=>queueStatus(b.dataset.qDel,'deleted'))}
  function queueStatus(id,status){let q=read(K.queue,[]);if(status==='deleted')q=q.filter(x=>x.id!==id);else q=q.map(x=>x.id===id?{...x,status}:x);write(K.queue,q);renderQueue()}
  function renderStaff(){const el=$('staffList');if(!el)return;el.innerHTML=users().map(x=>`<div class="team-row"><div><b>${esc(x.name)}</b><span>${esc(x.username)} · ${roles[x.role]||x.role}</span></div>${x.role!=='owner'?`<button data-staff-del="${x.id}">Hapus</button>`:''}</div>`).join('');el.querySelectorAll('[data-staff-del]').forEach(b=>b.onclick=()=>{write(K.users,users().filter(x=>x.id!==b.dataset.staffDel));renderStaff()})}
  function addStaff(){const name=prompt('Nama karyawan:');if(!name?.trim())return;const role=prompt('Role: manager / kitchen / waiter','waiter');if(!['manager','kitchen','waiter'].includes(role))return alert('Role tidak valid.');const username=prompt('Username:');const password=prompt('Password:');if(!username||!password)return;const u=users();if(u.some(x=>x.username===username))return alert('Username sudah dipakai.');u.push({id:uid(),name:name.trim(),username,password,role});write(K.users,u);renderStaff()}
  function boot(){if(window.__teamBooted)return;const s=session();if(!s)return;window.__teamBooted=true;injectStyles();addPages();moveLogoutToBottom();$('addStock').onclick=addStock;$('addStaff').onclick=addStaff;renderStock();renderQueue();renderStaff();if(s.role!=='owner'&&s.role!=='manager')$('staffTools')?.classList.add('team-locked');const sales=document.querySelector('.page-sales .page-heading');if(sales&&!document.querySelector('#staffRoleNote')){const n=document.createElement('div');n.id='staffRoleNote';n.className='team-box';n.style.marginTop='12px';n.innerHTML=s.role==='kitchen'?'<b>🍳 Mode Kitchen</b><small>Gunakan Operasional untuk stok, pemakaian, waste, dan sisa stok. Aktivitas akan masuk ke Owner.</small>':s.role==='waiter'?'<b>🧑‍🍳 Mode Waiter</b><small>Catat penjualan di halaman ini. Laporan tersimpan dan aktivitas bisa dipantau Owner.</small>':'<b>👑 Mode Owner</b><small>Akses penuh ke dashboard dan Team Ops.</small>';sales.appendChild(n)}}
  window.addEventListener('business-auth-ready',boot);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(session())boot()});else if(session())boot();
})();